spring:
  application:
    name: backend-template

  # 1. ??????? (???)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??????? url ?? backend ?????????????
    url: jdbc:mysql://localhost:3306/backend?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456  # ? ???????????? MySQL ????

  # 2. ?????????? 8 ????
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 3. Swagger ????
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  # ? ??????????????
  packages-to-scan: com.acha.project.controller

# 4. MyBatis Plus ?? (?? SQL ??)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true